# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a1fd94e78522b1fd0e90c83401c7eca01ceaad08af0609ab79a75df02a9433c78dffe958c9f4ebf641726cf36e378f9dba9ffa50fcdbc864e004e5257f4fe94

test:
  secret_key_base: 7471a89da695d9463d272c3c7f7015e988bb9e834ec0605bfbf6fdbc5e79b483d81171aaf075521e3471b1e2fc8edeaa1271b4314a5d169a22b3963b8866f79b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
